### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by AndreasEllwardt** [BetaMasaheft/Dillmann#122]
"ዘዘ
1062
ዝዕሜ | ዝየ
Latin
vid. sub ዘ፡ col. 1032. "

but the link goes to ዘ፡ col. 1028:

ዘ
1028
ማዕፈርት | ዝ
Latin
litera alphabeti Aethiopici decima septima, quae ዘይ፡ nominatur, cuique respondet زet ذ.

**Comment by PietroLiuzzo** [comment]
the link correctly goes to the record whose lemma is ዘ.  If the column indication in ዘዘ is wrong as the pdf link attests this can be edited by you within the app.

**Comment by AndreasEllwardt** [comment]
Not the column indication is wrong, but there is more than one ዘ, and it should go to ዘ፡ col. 1032 instead of going to ዘ፡ col. 1028. This is a wrong automatic linking.

**Comment by PietroLiuzzo** [comment]
off course not because they are dynamically generated, they are no where to be corrected by hand. but there is no mistake in the script which does what it should. We need to disambiguate the encoding. There is no ዘ on column 1032 in the pdf as far as I can see, the other ዘ entry starts at 1029 and ends at 1032. I think the best thing is to make that column reference an actual column reference and not a simple string. you need to encode col. as (col.) and 1032 as {DiL.1032}. The guidelines have instead an issue for me to fix

**Comment by PietroLiuzzo** [comment]
the guidelines have been fixed.

**Comment by PietroLiuzzo** [comment]
this is superseeded by the possibility to add an explicit link instead of relying on the automatic search for vid. in such cases
