### ISSUE TITLE
Creating a new Entry 

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#188]
I wanted to create a new entry, but unfortunately I am not able to ...

I received the following message:
Dear Susanne, unfortunately L9db555b4672341b0a6ca4932ea56d8c4 already exists! Please, hit the button below and try a different id.
http://betamasaheft.eu/Dillmann/edit/save-new-entity.xql

These are the data; I wanted to type in:

ታሕተ
TRACES

<Sen< 

>gez!taḥta>

+preposition+ 

>en> below, under, beneatḫ underneath; with suffix pronouns the base is ታሕቴ >gez!taḥte>
> 
[page,572b]bm:leslau1987dic 

{ND} 

((vid.)) \*gez*ታሕት፡\*

>S>

**Comment by PietroLiuzzo** [comment]
I tested creating this record. http://betamasaheft.eu/Dillmann/lemma/Lc5df1d93d73146d39aa6c28c8fee1772
and all went well. This means that I cannot reproduce this issue. Please try again with another term and let me know.

**Comment by PietroLiuzzo** [comment]
I have found the cause of the problem. it was again permissions. you could create a record, use an id but not edit the list of ids, so the app prevented you from creating a double picking again the same id. now I have restored the required permission setting to the list of ids, so that you can delete it once you create an item (the script does it) and the following user does not encounter any problem.
