### ISSUE TITLE
something to think about

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#200]
Some Ethiopian books have no author. If I give a reference to such a book in the lexicon, what appears is "Anon....."  (see the lemma በርባሮስ). Perhaps in such cases we would need to provide the title. 
What do you think?

**Comment by PietroLiuzzo** [comment]
this is indeed the standard behaviour when the information is correctly entered in Zotero. The bibliography guidance is correct and so is your encoding, @FrancescaPanini will also update the guidelines which indeed have an ambiguous formulation where they tell you to  
`If the name of the authors is not given and not known, use Anon. instead of the author's name.`
in these data entry guidelines it should simply tell you to omit the information.
https://github.com/BetaMasaheft/Documentation/wiki/zoteroguidelines
