### ISSUE TITLE
Sg. should also be visualized as singularis

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#212]
Could you please add for Sg. the extended form singularis (as it exists already for Pl. - pluralis)

I used it in 
http://betamasaheft.eu/Dillmann/lemma/L4ea04eb54d264fddb0bb8efa0444755f

**Comment by SusanneHummel** [comment]
SORRY! The correct title is:
Sg. should also be visualized as singularis

**Comment by PietroLiuzzo** [comment]
I did this change, but we need to be careful about consistence, because it seams to me that the other occurrences of labels abbreviating "Singularis" (which you can easily see checking the singularis box in the advanced options of the search) use the Sing. abbreviation, not Sg. if Sg. was used by Dillmann, then we missed quite a few of them in the intial markup phase which we can retrive now. This is true also if the proposed use was Sing but he actually uses Sg. if there is no other sign of the use of Sg. in Dillmann, I would advice to use the Sing. abbreviation which is already in use.
