### ISSUE TITLE
saving entries to personal list

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Dillmann#378]
It would actually be very cool if it were possible to save entries to a kind of personal vocabulary list, for personal studying purposes. Of course, I have no idea how complicated it would be.

**Comment by PietroLiuzzo** [comment]
your user page is not fine? https://betamasaheft.eu/user/Dorothea

**Comment by thea-m** [comment]
This lists the latest queries. I was thinking rather about a "save as favourite" option (for example, for me to save new words I want to learn, not all words I happen to click on)

**Comment by thea-m** [comment]
(and I actually don't find any Dillmann queries on the personal page? Where would they be?)

**Comment by PietroLiuzzo** [comment]
sorry, /Dillmann/user/Dorothea . no, there is no way to mark your favourite, interaction in the interface is limited. but there are pages you visited, which I think would stay up if they are really your favourite. otherwise I would suggest to use bookmarks or other similar third-parties solutions (e.g. hypothes.is), which will be more flexible, immediately available, and certainly meeting more needs, like grouping favourites, etc.

**Comment by thea-m** [comment]
ok, thank you
