### ISSUE TITLE
Entry ኅዱግ unavailable 

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#411]
When trying to get accest to the entry ኅዱግ the following message pops out:
![Screenshot 2022-03-17 113709](https://user-images.githubusercontent.com/29131132/158791658-90ab6b5e-7078-475b-a751-dbf359e692fa.png)

**Comment by eu-genia** [comment]
There is some problem with the data, can you give me the ID of the entry?

**Comment by MagdaKrzyz** [comment]
I got the ID of ሐለስትዮ. It doesn't open either.

https://betamasaheft.eu/Dillmann/lemma/Lc4c20ba1cc4f46e29067eada5f1c04fd

pt., 13 maj 2022 o 13:02 Magdalena Krzyżanowska ***@***.***>
napisał(a):

**Comment by eu-genia** [comment]
https://betamasaheft.eu/Dillmann/lemma/Lc4c20ba1cc4f46e29067eada5f1c04fd works all right for me

**Comment by eu-genia** [comment]
the direct link is https://betamasaheft.eu/Dillmann/?mode=none&q=%E1%8A%85%E1%8B%B1%E1%8C%8D&id=Lc169798f4e8c4a9c854be95b36421d15

the problem is in the query (search), when doing the search one gets the error because of some issue with multiple senses in the code line in app.xql calling for the edit button
```
             <div class="w3-quarter">{app:editineXide($id, <sources>{for $s in root($term)//tei:sense return <source lang="{$s/@xml:lang}" value="{$s/@source}"></source>}</sources>)}</div>
             </div>
```
I have commented it out for now

**Comment by MagdaKrzyz** [comment]
Zhenia,
I tried to enter ኅዱግ via ኀለስትዮ, which used to work some time ago but now
there is the same problem as with Hidug. Also ሥዩም - another possible word
via which one could enter Hidug does not function. I cannot help you here.



pt., 13 maj 2022 o 12:46 Magdalena Krzyżanowska ***@***.***>
napisał(a):

**Comment by eu-genia** [comment]
I am not quite sure what this refers to. Are you responding to an old email? This issue was closed long time ago (in May). 
https://betamasaheft.eu/Dillmann/lemma/Lc169798f4e8c4a9c854be95b36421d15 
https://betamasaheft.eu/Dillmann/lemma/Lc4c20ba1cc4f46e29067eada5f1c04fd
all work fine
If you want to open a new issue for a new error please do so and as always be very specific.
If you were cleaning old emails - please never react to issues per email but follow the link to github (https://github.com/BetaMasaheft/Dillmann/issues/411) to see the whole exchange before responding
Thank you!

**Comment by MagdaKrzyz** [comment]
That's the point! I cannot get there. But let me try to open the entry
through another one.

pt., 13 maj 2022 o 11:39 Eugenia ***@***.***> napisał(a):

**Comment by eu-genia** [comment]
Please do not work with issues via email. Go to https://github.com/BetaMasaheft/Dillmann/issues/411

What happens when you click on the links above?

**Comment by eu-genia** [comment]
Something strange is happening on GitHub. Are you getting old issues as emails? Are these latest recent responses or something that GitHub is suddenly resending?

**Comment by MagdaKrzyz** [comment]
Zhenia, no idea what is happening. It does not come from me.
