### ISSUE TITLE
Layout for Grebaut's entries 

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#426]
I have started working with Grebaut's Supplement. He uses indentation and new lines. To reflect more or less his layout I introduced the n-dash. Am I allowed to do it? You have introduced the n-dash for compounds under the label "Compound". I will not use this label here, hence the question. What do you think about how the entry is structured? Here an example: 
https://betamasaheft.eu/Dillmann/lemma/L6eb57b4154f4410c98848053aaaec9ff

I don't like that the bibliographical note referring to Grebaut's work stands out but I am following what we have done for Leslau.

**Comment by eu-genia** [comment]
unfortunately a series of n-dashes like this produces invalid XML (also in the case with compounds...), as each line should have its own - different - `xml:id`, there is now a team working with the code and they are very insistent that everything is valid, I shall have to go through compounds too 

for new data we should avoid this

and the XML also needs a language value assigned to the sense (always la for Dillmann, here probably should be fr)

I will try to explore how to make this valid data.

If you do not want to wait you can go on but please keep here a list of records you are creating so that I can then fix them once I know how. This is all not so easy.

**Comment by MagdaKrzyz** [comment]
I see. That is too bad. For Grebaut we need sth. neutral to distinguish different data. I wouldn't like to use indications for senses and subsenses because this will misrepresent Grebaut's work and I am not in the position to decide what is a sense and what a subsense. I have the impression that in some cases he simply compiled data under one entry. 
I will continue working on Grebaut without making any n-dashes --- just a stream of data. I will see what else would be needed for a better layout. 

Here are the entries with the compounds where I have used the n-dash: 
https://betamasaheft.eu/Dillmann/lemma/L153553e0e5e0448f9ba1221d2cf70045
https://betamasaheft.eu/Dillmann/lemma/Lef4ed3d79c8d44339fd73c7283d0123f
https://betamasaheft.eu/Dillmann/lemma/L1e32e08f156f4486bc3949b3fca5eeb8
https://betamasaheft.eu/Dillmann/lemma/L968149f7fc1748479a9f8482bc3f49c0
https://betamasaheft.eu/Dillmann/lemma/Lf6d41651ab0449f2ad1c8ebe891cb790
https://betamasaheft.eu/Dillmann/lemma/L5bc9c13e2ade4ff4b36198a957d94102
https://betamasaheft.eu/Dillmann/lemma/L33a2c869e7e343a0859911ef499b9068

As for the language, this is also an issue. I have always used English as the default language of the whole Traces section. This is because within this section different languages appear. I use a particular language only for example sentences.  In the case of ሀልዎ for the moment there is only Grebaut but I may add some more data in the future. Does it make sense?

**Comment by eu-genia** [comment]
i will have to study the code and try to find fixes, it all takes time.

**Comment by eu-genia** [comment]
You see in XML you cannot simply do layouting without attributing meanings to layouted elements.
For example, in a book you have a header in bold and for example a footnote number in bold. For XML you must say that the header is `<title>` and the footnote number is `<fn>`. At another step you can define how these are displayed (bold, italic, big, small, new line, above the line, any way you like).
So in order to assign lines you first need to know what these lines are.
The set of elements in TEI for a dictionary is relatively limited https://www.tei-c.org/release/doc/tei-p5-doc/en/html/DI.html

**Comment by eu-genia** [comment]
OK
Now if you want to have a new line just for the sake of a nice layout you can use the code `{LB}`, this should simply introduce the `<lb/>`, that is a line break

You can try it out

Please also list here the other lemmas you have created for Grebaut, there is some other possible issue, I might have to do something about it

**Comment by eu-genia** [comment]
no wait still something not working (

**Comment by eu-genia** [comment]
line breaks work all right, I have now re-edited https://betamasaheft.eu/Dillmann/lemma/L6eb57b4154f4410c98848053aaaec9ff, have a look

let me know if this same can be acceptable for compounds, then I will simply do line breaks there

**Comment by eu-genia** [comment]
still line breaks are really things that have no meaning. note that ideally mark up should be meaningful. 

the lack of structure is well seen if you switch from text to table view (actually probably the table view now makes little sense...)

**Comment by eu-genia** [comment]
can we use line breaks in compounds? if yes I will quickly do it and close this issue )

**Comment by eu-genia** [comment]
(or rather, I will open this one for now, and if more is needed for compounds i will reopen the compounds issue and work from there https://github.com/BetaMasaheft/Dillmann/issues/420)
